#!/bin/bash

PROJECT_HOME=$(dirname "$0")/..
DENO_BCI=../bci-deno/bci.ts

ASM_TESTS_HOME=../../scenarios/bci-asm
OPCODE_TESTS_HOME=../../scenarios/bci-opcode
TLCA_TESTS_HOME=../../scenarios/tlca

build_bci() {
    echo "---| build bci"
    zig build || exit 1
}

build_asm_tests() {
    echo "---| assemble scenario tests"

    for FILE in "$ASM_TESTS_HOME"/*.bci; do
        echo "- scenario test: $FILE"
        deno run --allow-read --allow-write "$DENO_BCI" asm "$FILE" || exit 1
    done
}

build_tlca_tests() {
    echo "---| assemble tlca tests"

    ../kotlin/tasks/dev parser || exit 1
    ../kotlin/tasks/dev jar || exit 1
    ../kotlin/tasks/dev compiler_scenario || exit 1
}

asm_tests() {
    echo "---| run asm tests"

    for FILE in "$ASM_TESTS_HOME"/*.bci; do
        echo "- asm test: $FILE"

        OUTPUT_BIN_FILE="$ASM_TESTS_HOME"/$(basename "$FILE" .bci).bin
        OUTPUT_OUT_FILE="$ASM_TESTS_HOME"/$(basename "$FILE" .bci).out

        zig-out/bin/bci-zig run "$OUTPUT_BIN_FILE" > t.txt || exit 1

        if ! diff -q "$OUTPUT_OUT_FILE" t.txt; then
            echo "asm test failed: $FILE"
            diff "$OUTPUT_OUT_FILE" t.txt
            rm t.txt
            exit 1
        fi

        rm t.txt
    done
}

opcode_tests() {
    echo "---| run opcode tests"

    for FILE in "$OPCODE_TESTS_HOME"/*.bci; do
        echo "- opcode test: $FILE"

	OUTPUT_BIN_FILE="$OPCODE_TESTS_HOME"/$(basename "$FILE" .bci).bin
	OUTPUT_OUT_FILE="$OPCODE_TESTS_HOME"/$(basename "$FILE" .bci).out

        deno run --allow-read --allow-write "$DENO_BCI" asm "$FILE" || exit 1
        zig-out/bin/bci-zig run "$OUTPUT_BIN_FILE" > t.txt || exit 1

        if grep -q "Memory leak detected" t.txt; then
            echo "scenario test failed: $FILE"
            echo "Memory leak detected"
            rm t.txt
            exit 1
        fi

        grep -v "^gc" t.txt > t2.txt
        if ! diff -q "$OUTPUT_OUT_FILE" t2.txt; then
            echo "scenario test failed: $FILE"
            diff "$OUTPUT_OUT_FILE" t2.txt
            rm t.txt t2.txt
            exit 1
        fi


        rm t.txt t2.txt
    done
}

tlca_tests() {
    echo "---| run tlca tests"

    for FILE in "$TLCA_TESTS_HOME"/*.inp; do
        echo "- tlca test: $FILE"

        OUTPUT_BIN_FILE="$TLCA_TESTS_HOME"/$(basename "$FILE" .inp).bin
        OUTPUT_OUT_FILE="$TLCA_TESTS_HOME"/$(basename "$FILE" .inp).out

        zig-out/bin/bci-zig run "$OUTPUT_BIN_FILE" > t.txt || exit 1

        if ! diff -q "$OUTPUT_OUT_FILE" t.txt; then
            echo "asm test failed: $FILE"
            diff "$OUTPUT_OUT_FILE" t.txt
            rm t.txt
            exit 1
        fi

        rm t.txt
    done
}

cd "$PROJECT_HOME" || exit 1

case "$1" in
"" | help)
    echo "Usage: $0 [<command>]"
    echo "Commands:"
    echo "  help"
    echo "    This help page"
    echo "  asm-tests"
    echo "    Run the different scenario tests"
    echo "  build-asm"
    echo "    Build the asm tests"
    echo "  build-tlca"
    echo "    Build the tlca tests"
    echo "  bci"
    echo "    Build the bci - bytecode interpreter"
    echo "  opcode-tests"
    echo "    Run the different opcode tests"
    echo "  tlca-tests"
    echo "    Run the different tlca tests"
    echo "  run"
    echo "    Run all tasks"
    ;;

asm-tests)
    asm_tests
    ;;

bci)
    build_bci
    ;;

build-asm)
    build_asm_tests
    ;;

asm-tests)
    asm_tests
    ;;

build-tlca)
    build_tlca_tests
    ;;

opcode-tests)
    opcode_tests
    ;;

tlca-tests)
    tlca_tests
    ;;

run)
    build_bci
    opcode_tests
    build_asm_tests
    asm_tests
    build_tlca_tests
    tlca_tests
    ;;

*)
    echo "$0: $1: Unknown command"
    exit 1
    ;;
esac
